### ISSUE TITLE
402::Unknown client should be 403::Unknown client

### ISSUE THREAD

**Issue by ivanpricewaycom** [SalesforceFoundation/python-bayeux#1]
Hi there,

in the code there are specific filters for "402::Unknown client", to detect when SF (for a reason i don't understand) drops the session / forgets our client.

However we are seeing "403::Unknown client".

we have removed the numeric code from the error message that we search on, on lines 192 and 287.

an extract from our log follows:

```
sf-listener_1    | 2017-05-05 09:12:09,049 INFO _send_message(): payload: {'channel': '/meta/connect', 'connectionType': 'long-polling', 'clientId': 'w1gk090q2qb5mf1w785zmh5agew', 'id': '1585'}  kwargs: {'timeout': 110.0}
sf-listener_1    | 2017-05-05 09:12:09,076 INFO _send_message(): response status code: 200  response.text: [{"advice":{"interval":0,"reconnect":"handshake"},"channel":"/meta/connect","id":"1585","error":"403::Unknown client","successful":false}]
```
cheers

**Comment by adamlincoln** [comment]
Release 0.1.3 fixes this.  Thanks for the report!
